name: DevSecOps Main Pipeline

on:
  push:
    branches: [ main, devsecops ]
  pull_request:
    branches: [ main, devsecops ]
  workflow_dispatch:

jobs:
  ci:
    name: CI Security Scanning
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  build:
    name: Build & Container Security
    needs: ci
    uses: ./.github/workflows/build.yml
    secrets: inherit

  cd:
    name: Continuous Deployment & DAST
    needs: build
    uses: ./.github/workflows/cd.yml
    secrets: inherit
